export const MET_OFFICE = [
  'Clear night',
  'Sunny day',
  'Partly cloudy (night)',
  'Sunny intervals',
  'Mist',
  'Fog',
  'Cloudy',
  'Overcast',
  'Light rain shower (night)',
  'Light rain shower (day)',
  'Drizzle',
  'Light rain',
  'Heavy rain shower (night)',
  'Heavy rain shower (day)',
  'Heavy rain',
  'Sleet shower (night)',
  'Sleet shower (day)',
  'Sleet',
  'Hail shower (night)',
  'Hail shower (day)',
  'Hail',
  'Light snow shower (night)',
  'Light snow shower (day)',
  'Light snow',
  'Heavy snow shower (night)',
  'Heavy snow shower (day)',
  'Heavy snow',
  'Thunder shower (night)',
  'Thunder shower (day)',
  'Thunder',
  'No data'
]

// Not complete -couldn't find them all
export const BBC = [
  'Clear Sky',
  'Sunny',
  'Sunny Intervals',
  'Partly Cloudy',
  'Light Cloud',
  'Thick Cloud',
  'Mist',
  'Fog',
  'Drizzle',
  'Light Rain Shower',
  'Light Rain',
  'Heavy Rain Shower',
  'Heavy Rain'
]

// Not complete - not including rare ones (eg 'sand' or 'smoke')
export const OPEN_WEATHER_MAP = [
  'clear sky',
  'few clouds',
  'scattered clouds',
  'broken clouds',
  'overcast clouds',
  'mist',
  'haze',
  'fog',
  'light intensity drizzle',
  'drizzle',
  'heavy intensity drizzle',
  'light intensity drizzle rain',
  'drizzle rain',
  'heavy intensity drizzle rain',
  'shower rain and drizzle',
  'heavy shower rain and drizzle',
  'shower drizzle',
  'light rain',
  'moderate rain',
  'heavy intensity rain',
  'very heavy rain',
  'extreme rain',
  'freezing rain',
  'light intensity shower rain',
  'shower rain',
  'heavy intensity shower rain',
  'ragged shower rain',
  'light snow',
  'snow',
  'heavy snow',
  'sleet',
  'shower sleet',
  'light rain and snow',
  'rain and snow',
  'light shower snow',
  'shower snow',
  'heavy shower snow',
  'thunderstorm with light rain',
  'thunderstorm with rain',
  'thunderstorm with heavy rain',
  'light thunderstorm',
  'thunderstorm',
  'heavy thunderstorm',
  'ragged thunderstorm',
  'thunderstorm with light drizzle',
  'thunderstorm with drizzle',
  'thunderstorm with heavy drizzle'
]

const translatableMetOffice = MET_OFFICE.filter(code => code !== 'No data');

export const TRANSALATABLE_CODES = translatableMetOffice.concat(BBC).concat(OPEN_WEATHER_MAP);
